### PR TITLE
fix mailing list "subscribe" link

### PR DESCRIPTION
**Pull request by jamescassell**

### CODE REVIEW

**Comment by dwlehman** [comment]
Thanks, @jamescassell -- I was just in the process of doing this myself.

**Comment by jtulak** [comment]
Merging.

**Comment by jtulak** [comment]
Btw, guys, I see I didn't add anyone else as a springfield-project member. I thought I put someone there... :( Should I add you @dwlehman?

**Comment by dwlehman** [comment]
Yes, please :) Thanks, @jtulak

**Pull request merged**
